export PYTHONPATH='.'
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_0
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_1
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_2
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_3
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_4
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_5
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_6
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_7
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_8
bash bash_helpers/run_paper_test_detailed_metrics.sh for_instance_no_outer_sparse_many_times/sparse_9

echo "Done with all tests"